Feature/reunioes
TreinaDev/td11-cola-bora pull request #37
Opened 2024-01-25 15:47 UTC by adoniranfranceh

### O que alcançamos com este PR

Adicionamos CRUD de Reuniões e implementamos papel de colaborador. Fizemos a lógica do criador do usuário se tornar um líder ao criar o projeto automaticamente. 
Configuramos a autorização a projetos e reuniões onde apenas o participantes do projeto tem acesso ao mesmo, atravez da sua User Role

- Tela de criação de reunião 
![image](https://github.com/TreinaDev/td11-cola-bora/assets/116985618/d1af1e48-df5b-4a74-834b-c6b04831a89f)
- Tela de edição de reunião
![image](https://github.com/TreinaDev/td11-cola-bora/assets/116985618/afdf2507-c9aa-4acf-8bb6-50b67bf67c62)

- Tela de listagem de reuniões 
A listagem é feita por ordem crescente e cada dia que tem reunião aparece o cabeçalho com a data e abaixo as reuniões desse dia
![image](https://github.com/TreinaDev/td11-cola-bora/assets/116985618/76103fc1-8f9c-40a1-ba77-f3e2efdea69b)

- Tela de detalhes de reunião
![image](https://github.com/TreinaDev/td11-cola-bora/assets/116985618/bd5cce5d-f5ba-44aa-83b5-1097a0b538cf)

### Débitos
-  Acreditamos que o PR estava ficando muito grande e decidimos dividi-lo ao meio.
-  Teste de sistema para a listagem de reuniões na ordem em grupo
-  A listagem de reuniões deve aparecer apenas reuniões que você é um participantes
-  A logica de convite para reunião

2024-01-25 16:48 UTC, joaorsalmeida requested changes
Pessoal, achei uns pontos que valem ao menos uma revisão de vocês. Vejam o que acham.

2024-01-25 17:05 UTC, adoniranfranceh commented on spec/models/meeting_spec.rb
> +        meeting = FactoryBot.build(:meeting, datetime: (Time.zone.now + 1.hour))
Não implementamos. Mas seria uma boa fazer dessa forma.

2024-01-25 22:56 UTC, joaorsalmeida approved these changes

2024-01-26 11:41 UTC, fredericomozzato approved these changes
Deixei alguns comentário mas nada demais. Inclusive peguei algumas ideias de vocês pros meus testes!

2024-01-26 11:41 UTC, fredericomozzato commented on spec/models/meeting_spec.rb
> +        meeting = FactoryBot.build(:meeting, title: '')
O projeto está configurado para o uso direto dos métodos do FactoryBot sem precisar chamar a classe. Podemos só chamar create, build etc. Dá pra economizar muito teclado com isso heeheh

2024-01-26 13:04 UTC, merged

2024-01-27 00:59 UTC, Luckvc commented on app/models/user.rb
> +    user_role = UserRole.get_user_role(meeting.project, self)
Sei que já foi resolvido, mas estou dando umas olhadas nos prs. O get_user_role será usado em outros lugares, ai foi só uma questão de já ter o método, mas acredito que no final da na mesma, mas é uma chamada de método a menos na pilha.