Feature/lider ve perfil completo
TreinaDev/td11-cola-bora pull request #40
Opened 2024-01-26 15:15 UTC by olucasaguilar

Resolve a issue #27.

Este PR adiciona a página de perfil completo de um usuário.

Os dados do usuário vem da API da Portfoliorrr.

Quando o usuário da Cola?Bora! entra na página de perfil completo, uma requisição é disparada para a API retornar os dados.

O botão para acessar a página foi adicionado na tela de listagem de perfis (que também utiliza a API da Portfoliorrr).

Apenas líder de um projeto pode acessar essa página de perfil completo, assim como apenas líder pode acessar a listagem de usuários.

Foi tratado para que, caso a API não retorne os dados corretamente, uma mensagem personalizada aparece na página.

(Esse PR cria apenas a página de perfil completo. A página da listagem de perfis já foi implementada em outra PR)

---

### Prints

Listagem de perfis, onde  nome da pessoa foi alterado para um link

![Screenshot_1](https://github.com/TreinaDev/td11-cola-bora/assets/69739994/c9b78f09-ee7e-47d6-b851-c4016cdcf33b)

Página de perfil completo, com dados

![Screenshot_2](https://github.com/TreinaDev/td11-cola-bora/assets/69739994/405d6bf9-8e26-45c0-b43b-7b31fb34e0ea)

Página de perfil completo, sem os dados

![Screenshot_3](https://github.com/TreinaDev/td11-cola-bora/assets/69739994/ccf9052e-382f-4001-b717-834db10ec038)

### Débitos

- Não adicionamos o botão de convite na página de perfil pois isso será feito em outra PR
- Assim que a API da Portfoliorrr ficar pronta, teremos que adaptar o nosso sistema para receber os dados exatos que a API enviar.

2024-01-26 20:20 UTC, adoniranfranceh requested changes
Olá gente. Gostei da ideia do código de vocês. Deixei apenas uma observação simples.

2024-01-26 20:20 UTC, adoniranfranceh commented on spec/system/projects/portfoliorrr_profiles/leader_views_portfoliorrr_profile_details_spec.rb
> +  it 'e precisa ter vínculo com o projeto' do
Vendo que a URL compartilha o id do projeto, seria legal o seguinte cenário para testar: 'e não pode ser líder de outro projeto'. Porque deixaria claro que URL para acessar detalhes de perfis da portfoliorrr é única para cada projeto, e é preciso ser condizente com o projeto do Líder atual.

2024-01-27 14:16 UTC, paulohenrique-gh approved these changes
Bom trabalho, pessoal! O código me parece organizado, os testes cobrem diversos cenários. Concordo com a sugestão do Adoniran de incluir teste para garantir que um líder não acesse a página de pesquisa em um projeto de outro líder. Fora isso, o código está bem escrito e com boa legibilidade, deu até pra pegar uns macetes novos  😁

2024-01-27 16:11 UTC, fredericomozzato approved these changes
Deixei alguns comentários sobre pontos que podem ser melhorados, mas nada grave ou que precise ser modificado, apenas detalhes mesmo. 

Mas no geral ficou bom, então já estou aprovando!

2024-01-27 16:11 UTC, fredericomozzato commented on app/views/portfoliorrr_profiles/search.html.erb
> +            </p>
Pelo que entendi esse elemento faz a união das categorias que estão em um array em uma frase com cada categoria separada por vírgulas, certo? Caso seja isso, eu recomento vocês chamarem o método `to_sentence` no array, que faz exatamente isso e ainda conecta o último elemento com um 'e', que vocês podem passar como parâmetro. Ele ainda suporta I18N que vocês podem configurar.

Não é necessário, mas ajuda a deixar o código mais legível.

[LINK](https://apidock.com/rails/Array/to_sentence) da documentação do método.

2024-01-27 22:36 UTC, paulohenrique-gh commented on app/views/portfoliorrr_profiles/show.html.erb
Pessoal, acredito que ficaria interessante incluir nessa página também o nome do projeto para o qual o líder está buscando colaborador.

Poderia ficar algo do tipo:

<h1>[Nome do projeto] - Recrutamento de colaboradores</h1>

2024-01-27 22:36 UTC, paulohenrique-gh commented
Incluir só uma sugestão pra página do perfil do usuário Portfoliorrr

2024-01-28 15:34 UTC, Luckvc commented on app/controllers/portfoliorrr_profiles_controller.rb
> +  end
Código muito bem escrito, só fiquei em dúvida nessa questão. 
Nesses dois métodos que estão rodando em todas as actions, vocês primeiro perguntam se o current_user é um membro daquele projeto e depois se ele é o líder daquele projeto. 

Se a ideia é que apenas o líder daquele projeto tenha acesso à essas páginas. Se vocês testarem só se o current_user é o líder daquele projeto, não chegam ao mesmo resultado?

2024-01-28 15:38 UTC, Luckvc approved these changes

2024-01-29 13:00 UTC, olucasaguilar commented on spec/system/projects/portfoliorrr_profiles/leader_views_portfoliorrr_profile_details_spec.rb
> +  it 'e precisa ter vínculo com o projeto' do
Boa observação. Pensando na sua sugestão a gente fez algumas alterações nos testes, de forma que ficou mais claro essa questão de ser líder apenas do projeto "atual", e não de outro.

2024-01-29 13:26 UTC, olucasaguilar commented on app/views/portfoliorrr_profiles/show.html.erb
Boa. Fizemos a adição desse título :D

2024-01-29 13:27 UTC, olucasaguilar commented on app/views/portfoliorrr_profiles/search.html.erb
> +            </p>
Fizemos uma mudança e incluímos o método. Vlw Fred

2024-01-29 13:33 UTC, olucasaguilar commented on app/controllers/portfoliorrr_profiles_controller.rb
> +  end
Boa Lucas. A gente colocou as duas validações pois só a `leader?` quebrava quando o usuário não era membro. Mas pensando bem, depois que você nos questionou, a gente refatorou para, dentro de `leader?` também chamar o `member?`. Assim, a gente só chama o `leader?` e já valida os dois.

Ficou assim no controller de projeto:

```ruby
def leader?(user)
  member?(user) && user_roles.find_by(user:).leader?
end
```

2024-01-29 13:35 UTC, OtavioLins approved these changes
Fiz o comentário apenas em relação a um teste. No mais, acho que está ok :)

2024-01-29 13:35 UTC, OtavioLins commented on spec/models/project_spec.rb
> +  context '#member?' do
Um teste que eu acho bacana de fazer também é um que um usuário tem vínculo com um projeto, mas não o projeto ao qual você está chamando o `member?`, para garantir que o método não retorna true sempre que um usuário tem vínculo com um projeto, mesmo não sendo o que vocês estão buscando

2024-01-29 13:48 UTC, olucasaguilar commented on app/controllers/portfoliorrr_profiles_controller.rb
> +  before_action :authenticate_user!, only: %i[search show]
Fizemos a alteração disso :D

2024-01-29 13:48 UTC, olucasaguilar commented on spec/system/projects/portfoliorrr_profiles/leader_views_portfoliorrr_profile_details_spec.rb
> +    user = create :user, cpf: '149.759.780-32', email: 'contributor@email.com'
Fizemos a alteração disso :D

2024-01-29 14:01 UTC, olucasaguilar commented on spec/models/project_spec.rb
> +  context '#member?' do
Boa. Criamos esse teste. Também fizemos o teste para `#leader?`, garantinho que lider de outro projeto retorna `false`

2024-01-29 14:53 UTC, adoniranfranceh approved these changes

2024-01-29 14:56 UTC, merged