Feature/lider envia convite
TreinaDev/td11-cola-bora pull request #42
Opened 2024-01-27 00:32 UTC by paulohenrique-gh

Esse PR resolve as issues #24 e #41

## Líder envia convite: 

Fizemos a criação do convite.
O convite no momento tem 3 status validados:
  - pending: Convite pendente de resposta 
  - cancelled: Convite cancelado pelo líder do projeto
  - expired: Convite expirado

Só é possível mudar o status do convite se o status atual for ```pending```.

Criamos um endpoint para consulta de convites: ```api/v1/invitations?id=2```
Parâmetro:
- ID: ID do usuário do Portfoliorrr
Retorna uma coleção com convites pendentes a partir do ID do usuário informado em formato JSON

## Líder revoga convite:

Implementamos a funcionalidade para o líder cancelar o convite se ainda estiver pendente, e para enviar outro se estiver expirado ou cancelado

------

## Prints
Formulário para criação do convite na página do perfil do usuário Portfoliorrr (fizemos sem detalhes do perfil pois está sendo implementado em outro PR)
![image](https://github.com/TreinaDev/td11-cola-bora/assets/124916478/1a862cda-c2d4-42bd-91f8-9e7a44c19dba)

Opção para cancelar o convite pendente
![image](https://github.com/TreinaDev/td11-cola-bora/assets/124916478/5f39c068-4330-4d08-ad06-dc23e76a4d27)

------

## Débitos
- Implementação de jobs para atualizar o status para expirado quando o convite estiver vencido.
- Possível necessidade de adaptação no código quando a equipe Portfoliorrr implementar os endpoints de consulta de usuário

2024-01-27 17:14 UTC, fredericomozzato requested changes
Pessoal, acredito que somente aquelas questões dos matchers truthy e falsy deveriam ser ajustadas pra garantir que os testes esperam booleanos mesmo, evitando falsos positivos/negativos.

De resto está legal.

2024-01-27 17:14 UTC, fredericomozzato commented on app/controllers/invitations_controller.rb
> +  before_action :authenticate_user!, only: %i[create cancel]
A main já está com o método de autenticação no ApplicationController, então todas as actions de todos os controllers estão fechadas. Quando forem resolver os conflitos podem tirar esta linha que vai continuar funcionando certinho.

2024-01-27 20:23 UTC, adoniranfranceh approved these changes

2024-01-29 12:57 UTC, OtavioLins reviewed
Deixei vários comentários de coisinhas que me chamaram atenção.

Sobre os prints, me parece importante ter um histórico de convites ali na tela que vocês estão exibindo, pois me parece que o líder não tem como ver se ele já enviou um convite para esse usuário e, depois, cancelou.

2024-01-29 12:57 UTC, OtavioLins commented on app/controllers/api/v1/api_controller.rb
Que estranho esse arquivo aparecer aqui sendo que ele já está na main 🤔

2024-01-29 12:57 UTC, OtavioLins commented on app/controllers/portfoliorrr_profiles_controller.rb
O que exatamente do perfil está sendo implementado em outro PR? É bom especificar, pois como vocês adicionaram um controler para o perfil do usuário nesse PR, acaba ficando bem confuso, pois me pareceu que nada do perfil estaria aqui sabe?

2024-01-29 13:09 UTC, paulohenrique-gh commented on app/controllers/portfoliorrr_profiles_controller.rb
Incluímos apenas o formulário de convite que vai estar dentro da página de perfil do usuário Portfoliorrr que está sendo implementada no PR #40. Inclui isso na descrição do PR agora

2024-01-29 13:20 UTC, valerialrc commented on app/models/invitation.rb
> +  validate :pending_invitation_for_current_project, on: :create
Alteramos o nome do método. Nos testes unitários nós testamos este caso e agora testei manualmente no console também e não foi possível forçar, a lógica dos métodos de atualização de status também foi sobrescrita no model.

2024-01-29 13:24 UTC, valerialrc commented on app/models/portfoliorrr_profile.rb
Aqui não fizemos nenhuma alteração, só incluimos o arquivo do PR #36 para poder usar a lógica que já tinha sido feita nele, foi uma sugestão do João.

2024-01-29 13:33 UTC, valerialrc commented on spec/models/invitation_spec.rb
> +    context 'retorna verdadeiro se tentar mudar de cancelled para qualquer outro' do
A lógica no model está travada para não aceitar alterar nenhum convite para pendente em qualquer cenário. Mas adicionamos o teste sugerido.

2024-01-29 13:36 UTC, valerialrc commented on spec/requests/api/invitation_search_api_spec.rb
> +describe 'Invitation search API' do
O teste 'retorna vazio quando não existem convites para o usuário' já avalia este cenário. Se não ouver nenhum convite para o id passado, a resposta será um array vazio.

2024-01-29 13:42 UTC, valerialrc commented on spec/system/invitations/user_send_invitation_spec.rb
Os testes de autorização foram feitos como testes de request, mas vamos adicionar um teste só para checar se um usuário não autorizado consegue visualizar o formulário de convite.

2024-01-29 13:44 UTC, valerialrc commented
> Deixei vários comentários de coisinhas que me chamaram atenção.
> 
> Sobre os prints, me parece importante ter um histórico de convites ali na tela que vocês estão exibindo, pois me parece que o líder não tem como ver se ele já enviou um convite para esse usuário e, depois, cancelou.

Vamos adicionar uma nova issue para tratar este caso. Não pensamos nessa funcionalidade.

2024-01-29 13:49 UTC, fredericomozzato approved these changes

2024-01-29 13:55 UTC, merged